### ISSUE TITLE
Destroys avatar's mesh on higher distorts

### ISSUE THREAD

**Issue by OFWModz** [rygo6/GTAvaCrypt#2]
See screenshot, can't recover mesh either as it was a .asset mesh file due to losing files in the past.

![image](https://user-images.githubusercontent.com/36628963/107169478-d5afd700-69b5-11eb-9dc6-e35f1fedcb26.png)

**Comment by rygo6** [comment]
Hello. Pleased to see someone managed to find this repo so soon after I posted it.

The "_Encrypted" mesh and avatar GameObject should appear completely distorted like that in the editor. You would need to put the keys into the shader to test it in the editor. At the bottom of GTPoiyomiShader you should see "Key" 0-4 where you could enter those values.

But it looks like it affected your Avatar's original GameObject too? That shouldn't actually happen at all. It should make a copy of your avatars GameObject, and also a copy of any meshes it edits. The copies should have _Encrypted after them. Is that not what happened?

**Comment by OFWModz** [comment]
What you see is the original one. My mesh is a .asset, not fbx.

I have also advertised this af in my server and would like to talk in a better fassion. Please hmu at Plague#2850

**Comment by rygo6** [comment]
I see what the problem is. I pushed a fix for this.

Thanks for being literally the first tester of this. But I apologize for it wrecking your original mesh. Do you have a back up of your mesh? If not I can add a method you could run to un-obfuscate the mesh.

I tried to add you on discord.

**Comment by OFWModz** [comment]
Add Plague#9351, forgot 2850 went doot.
