### ISSUE TITLE
Mesh encryption destroys cloth constraints

### ISSUE THREAD

**Issue by Ess-Ka** [rygo6/GTAvaCrypt#4]
With the encryption of the mesh, the cloth components loses their constraints. The result is, that the cloth fell off from an avatar in play mode.

Before encryption:
![grafik](https://user-images.githubusercontent.com/84975839/119990796-0e0d0c80-bfc9-11eb-84ab-447de9db5747.png)

After encryption:
![grafik](https://user-images.githubusercontent.com/84975839/119990897-29781780-bfc9-11eb-838e-b0a1c8f82bc5.png)

**Comment by Ess-Ka** [comment]
If there ist no solution for it, maybe it could make sense to create a "AvaDoNotEntcrypt" component, which flags (skinned) mesh rendereres, which should not be encryped.

**Comment by Ess-Ka** [comment]
With this enhanced logic, it would be theoratically possible, to remap the cloth constraints:
```
            foreach (SkinnedMeshRenderer skinnedMeshRenderer in skinnedMeshRenderers)
            {
                var Materials = skinnedMeshRenderer.sharedMaterials;
                var cloth = skinnedMeshRenderer.GetComponent<Cloth>();

                foreach (var Material in Materials)
                {
                    if (Material.HasProperty("_Key0"))
                    {
                        ClothSkinningCoefficient[] savedCoefficients = null;

                        if (cloth != null)
                        {
                            Debug.Log("Vertices before: " + cloth.vertices.Length);

                            savedCoefficients = new ClothSkinningCoefficient[cloth.vertices.Length];

                            for (int i = 0; i < savedCoefficients.Length; i++) 
                            {
                                savedCoefficients[i] = cloth.coefficients[i];
                            }
                        }

                        skinnedMeshRenderer.sharedMesh = _avaCryptMesh.EncryptMesh(skinnedMeshRenderer.sharedMesh, _key0, _key1, _key2, _key3, _distortRatio);

                        if (cloth != null)
                        {
                            Debug.Log("Vertices after: " +  cloth.vertices.Length);

                            ClothSkinningCoefficient[] coefficients = cloth.coefficients;

                            // for (int i = 0; i < coefficients.Length; i++) <-- has other array size
                            for (int i = 0; i < savedCoefficients.Length; i++)
                            {
                                coefficients[i] = savedCoefficients[i];
                            }

                            cloth.coefficients = coefficients;
                        }

                        break;
                    }
                }
            }
```

The problem is - the amount of vertices is not the same anymore after the encryption:
![grafik](https://user-images.githubusercontent.com/84975839/120004817-81b61600-bfd7-11eb-8012-9fe169e518f1.png)

Uncompleted result:
![grafik](https://user-images.githubusercontent.com/84975839/120004544-30a62200-bfd7-11eb-99c2-2f90d5fcb77f.png)

I guess, vertices which are usually on the same place, will move appart during encryption and results to an higher amount of vertices.

**Comment by rygo6** [comment]
Hm yes. Never used it on cloth, I wouldn't expect it to work there.

Does adding the cloth.coefficients produce the correct simulation? I assume cloth simulation is dependent on the structure of the mesh, and if you moved cloth vertices it would somehow mess with the simulation.

**Comment by Ess-Ka** [comment]
Yes, the cloth component uses the mesh of the skinnend mesh renderer. My mesh has 720 veritces. It looks, like on the cloth-component, the mesh is internal optimized and vertices on same place will be removed/merged. This results in 328 vertices there. 

So my idea was, to encrypt vertices on same positions with same parameters. With this logic, it works with cloth - the amount don't change anymore and the transfer of cloth.coefficients works well. Here my example:

AvaCryptRoot.EncryptAvatar():
```
            SkinnedMeshRenderer[] skinnedMeshRenderers = encodedGameObject.GetComponentsInChildren<SkinnedMeshRenderer>(true);
            foreach (SkinnedMeshRenderer skinnedMeshRenderer in skinnedMeshRenderers)
            {
                var Materials = skinnedMeshRenderer.sharedMaterials;
                var cloth = skinnedMeshRenderer.GetComponent<Cloth>();

                foreach (var Material in Materials)
                {
                    if (Material.HasProperty("_Key0"))
                    {
                        ClothSkinningCoefficient[] savedCoefficients = null;

                        if (cloth != null)
                        {
                            savedCoefficients = new ClothSkinningCoefficient[cloth.vertices.Length];

                            for (int i = 0; i < savedCoefficients.Length; i++) 
                            {
                                savedCoefficients[i] = cloth.coefficients[i];
                            }
                        }

                        skinnedMeshRenderer.sharedMesh = _avaCryptMesh.EncryptMesh(skinnedMeshRenderer.sharedMesh, _key0, _key1, _key2, _key3, _distortRatio);

                        if (cloth != null)
                        {
                            if (cloth.coefficients.Length == savedCoefficients.Length)
                            {
                                ClothSkinningCoefficient[] coefficients = cloth.coefficients;

                                for (int i = 0; i < savedCoefficients.Length; i++) 
                                {
                                    coefficients[i] = savedCoefficients[i];
                                }

                                cloth.coefficients = coefficients;
                            }
                            else
                            {
                                Debug.Log($"Cannot transerfer cloth constraints: {cloth.name}");
                            }
                        }

                        break;
                    }
                }
            }
```

As next the logic to find vertices on same positions. In this case, I take the values of the first similar vertice.

AvaCryptMesh.EncryptMesh():
```
           var minRange = maxDistance * -distortRatio;
            const float maxRange = 0;

            Dictionary<Vector3, int> sameVertices = new Dictionary<Vector3, int>();
    
            for (var v = 0; v < newVertices.Length; v++)
            {
                if (!sameVertices.ContainsKey(newVertices[v])) 
                {
                    sameVertices.Add(newVertices[v], v);

                    uv7Offsets[v].x = Random.Range(minRange, maxRange);
                    uv7Offsets[v].y = Random.Range(minRange, maxRange);

                    uv8Offsets[v].x = Random.Range(minRange, maxRange);
                    uv8Offsets[v].y = Random.Range(minRange, maxRange);

                    newVertices[v] += normals[v] * uv7Offsets[v].x * comKey0;
                    newVertices[v] += normals[v] * uv7Offsets[v].y * comKey1;
                    newVertices[v] += normals[v] * uv8Offsets[v].x * comKey2;
                    newVertices[v] += normals[v] * uv8Offsets[v].y * comKey3;
                }
                else 
                {
                    var index = sameVertices[newVertices[v]];

                    uv7Offsets[v].x = uv7Offsets[index].x;
                    uv7Offsets[v].y = uv7Offsets[index].y;

                    uv8Offsets[v].x = uv8Offsets[index].x;
                    uv8Offsets[v].y = uv8Offsets[index].y;

                    newVertices[v] = newVertices[index];
                }
            }
```

Result (decrypted):
![grafik](https://user-images.githubusercontent.com/84975839/120029292-2f382200-bff6-11eb-92ca-26eb444667d3.png)

So, this works better for cloth, but has still some visual artifacts. The reason is - the shader takes always the normals according to it's vertices. And this matches not with the normals[v] of my overriden vertices in my example.

**Comment by Ess-Ka** [comment]
My next idea was, to not use the normals as direction vectors for the offsets. Instead of normals, I can generate a random direction vector (Random.insideUnitSphere) and store it in the unused uv5/uv6 structure. So I can send overriden directions to the shader. This should solve the problem, but I dont know, if any additional parameters in the shader input structure results to an negative performance impact.

**Comment by rygo6** [comment]
Personally I'd tend towards just making it exclude anything with a cloth sim component.

**Comment by Ess-Ka** [comment]
Yes, this is a good solution too. Maybe add a warning during validation, so that it's clear for the user.

**Comment by rygo6** [comment]
Ya I think your the first to use this on something with clothing :P

**Comment by Ess-Ka** [comment]
If you have a fix and you can't test it, let me know. I can do some tests and give you a feedback.
